// Created by iWeb 3.0.4 local-build-20140612

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWPhotoFrame([IWCreateImage('ConcurrencyVerification2014_files/FormalShadow_01.png'),IWCreateImage('ConcurrencyVerification2014_files/FormalShadow_02.png'),IWCreateImage('ConcurrencyVerification2014_files/FormalShadow_03.png'),IWCreateImage('ConcurrencyVerification2014_files/FormalShadow_06.png'),IWCreateImage('ConcurrencyVerification2014_files/FormalShadow_12.png'),IWCreateImage('ConcurrencyVerification2014_files/FormalShadow_11.png'),IWCreateImage('ConcurrencyVerification2014_files/FormalShadow_10.png'),IWCreateImage('ConcurrencyVerification2014_files/FormalShadow_04.png')],null,2,0.700000,1.000000,5.000000,1.000000,4.000000,17.000000,17.000000,17.000000,36.000000,4.000000,837.000000,4.000000,837.000000,null,null,null,0.100000)});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('ConcurrencyVerification2014_files/ConcurrencyVerification2014Moz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');detectBrowser();adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');fixupAllIEPNGBGs();fixAllIEPNGs('Media/transparent.gif');fixupIECSS3Opacity('id10');Widget.onload();applyEffects()}
function onPageUnload()
{Widget.onunload();}
